import './globals.css';

export const metadata = {
  title: 'Project-X', 
  description: 'Generated by Project-X',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
