// app/layout.js

import "./globals.css";
import Header from "./components/Header"; // Ensure correct import for Header

export const metadata = {
  title: "SmartAppSolutions",
  description: "Generated by SmartAppSolutions",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className="antialiased">
        {/* Include Header */}
        <Header />

        {/* Render Page Content */}
        {children}

        {/* Footer Section */}
        <footer className="bg-gradient-to-b from-purple-500 to-blue-700 text-white text-center p-8 md:p-12">
          <p className="text-sm md:text-base">
            &copy; {new Date().getFullYear()} SmartAppSolutions. All Rights
            Reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
